name: infinite_widgets
description: Infinite layout widgets, allow you to easily create infinite list or infinite grid from database or network calls.
version: 2.0.0
homepage: https://github.com/jaumard/infinite_widgets

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
